<?php

namespace AppBundle\Repository;

/**
 * MyTableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MyTableRepository extends \Doctrine\ORM\EntityRepository
{
}
